apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-demo
  name: java-demo
  namespace: NS
spec:
  replicas: RSCOUNT
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      imagePullSecrets:
      - name: SECRET_NAME
      containers:
      - image: IMAGE_NAME
        name: java-demo

---

apiVersion: v1
kind: Service
metadata:
  name: java-demo
  namespace: NS
  labels:
    app: java-demo
spec:
  selector:
    app: java-demo
  ports:
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort


