apiVersion: v1
kind: Service
metadata:
  name: java-demo
  namespace: dev
  labels:
    app: java-demo
spec:
  selector:
    app: java-demo
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort

